[project]
name = "big-data-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "e-mace-ece", email = "erwan.mace@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
big-data-lab = "big_data_lab:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
